import { TechniqueConfig } from '../types'

export const TECHNIQUES: Record<string, TechniqueConfig> = {
  'nadi-shodhana': {
    id: 'nadi-shodhana',
    name: 'Nadi Shodhana',
    description: 'Alternate nostril breathing for balance and calm',
    benefits: [
      'Balances left and right hemispheres',
      'Reduces stress and anxiety',
      'Improves focus and concentration',
      'Calms the nervous system',
    ],
    defaultSettings: {
      inhale: 4,
      holdInhale: 4,
      exhale: 4,
      holdExhale: 0,
      cycles: 10,
      pace: 'medium',
    },
    instructions: [
      'Sit comfortably with spine straight',
      'Use right thumb to close right nostril',
      'Inhale through left nostril',
      'Close left nostril, open right, exhale',
      'Inhale through right nostril',
      'Close right, open left, exhale',
      'This completes one cycle',
    ],
    difficulty: 'beginner',
    duration: {
      min: 180,
      max: 1200,
      default: 300,
    },
  },
  ujjayi: {
    id: 'ujjayi',
    name: 'Ujjayi',
    description: 'Ocean breath for grounding and warmth',
    benefits: [
      'Increases oxygen intake',
      'Builds internal heat',
      'Improves concentration',
      'Calms the mind',
    ],
    defaultSettings: {
      inhale: 5,
      exhale: 5,
      holdInhale: 0,
      holdExhale: 0,
      cycles: 20,
      pace: 'slow',
    },
    instructions: [
      'Sit or lie comfortably',
      'Slightly constrict the back of your throat',
      'Breathe through your nose',
      'Create a soft ocean sound',
      'Keep the breath smooth and even',
      'Maintain the constriction on both inhale and exhale',
    ],
    difficulty: 'beginner',
    duration: {
      min: 180,
      max: 1800,
      default: 600,
    },
  },
  kapalbhati: {
    id: 'kapalbhati',
    name: 'Kapalbhati',
    description: 'Skull shining breath for energy and clarity',
    benefits: [
      'Energizes the body',
      'Clears the mind',
      'Strengthens abdominal muscles',
      'Improves digestion',
    ],
    defaultSettings: {
      inhale: 1,
      exhale: 0.5,
      holdInhale: 0,
      holdExhale: 0,
      cycles: 30,
      pace: 'fast',
    },
    instructions: [
      'Sit with spine straight',
      'Take a deep breath in',
      'Exhale forcefully through the nose',
      'Let the inhale happen passively',
      'Focus on short, powerful exhales',
      'Start with 30 cycles, rest, repeat',
    ],
    difficulty: 'intermediate',
    duration: {
      min: 60,
      max: 600,
      default: 180,
    },
  },
  bhramari: {
    id: 'bhramari',
    name: 'Bhramari',
    description: 'Bee breath for instant calm',
    benefits: [
      'Reduces stress immediately',
      'Lowers blood pressure',
      'Improves sleep quality',
      'Enhances focus',
    ],
    defaultSettings: {
      inhale: 4,
      exhale: 8,
      holdInhale: 0,
      holdExhale: 0,
      cycles: 8,
      pace: 'slow',
      soundEnabled: true,
    },
    instructions: [
      'Sit comfortably with eyes closed',
      'Place index fingers on ears (optional)',
      'Inhale deeply through the nose',
      'Exhale while making a humming sound',
      'Feel the vibration in your head',
      'Repeat 5-10 times',
    ],
    difficulty: 'beginner',
    duration: {
      min: 120,
      max: 600,
      default: 240,
    },
  },
  'wim-hof': {
    id: 'wim-hof',
    name: 'Wim Hof Method',
    description: 'Powerful breathing for energy and resilience',
    benefits: [
      'Increases energy levels',
      'Boosts immune system',
      'Reduces inflammation',
      'Improves mental clarity',
    ],
    defaultSettings: {
      inhale: 2,
      exhale: 2,
      holdInhale: 15,
      holdExhale: 0,
      cycles: 3,
      pace: 'fast',
    },
    instructions: [
      'Lie down or sit comfortably',
      'Take 30-40 deep, quick breaths',
      'Fully in through nose or mouth',
      'Let go without force on exhale',
      'After last exhale, hold breath',
      'Hold until you feel the urge to breathe',
      'Inhale deeply and hold for 15 seconds',
      'Repeat for 3 rounds',
    ],
    difficulty: 'advanced',
    duration: {
      min: 300,
      max: 1200,
      default: 600,
    },
  },
  'box-breathing': {
    id: 'box-breathing',
    name: 'Box Breathing',
    description: 'Four-square breathing for focus and calm',
    benefits: [
      'Reduces stress and anxiety',
      'Improves focus',
      'Regulates nervous system',
      'Enhances performance under pressure',
    ],
    defaultSettings: {
      inhale: 4,
      holdInhale: 4,
      exhale: 4,
      holdExhale: 4,
      cycles: 10,
      pace: 'medium',
    },
    instructions: [
      'Sit comfortably with spine straight',
      'Exhale all air from your lungs',
      'Inhale for 4 counts',
      'Hold for 4 counts',
      'Exhale for 4 counts',
      'Hold for 4 counts',
      'Repeat',
    ],
    difficulty: 'beginner',
    duration: {
      min: 120,
      max: 900,
      default: 300,
    },
  },
  '4-7-8': {
    id: '4-7-8',
    name: '4-7-8 Breathing',
    description: 'Relaxing breath for sleep and anxiety',
    benefits: [
      'Promotes deep relaxation',
      'Helps with falling asleep',
      'Reduces anxiety',
      'Lowers blood pressure',
    ],
    defaultSettings: {
      inhale: 4,
      holdInhale: 7,
      exhale: 8,
      holdExhale: 0,
      cycles: 4,
      pace: 'slow',
    },
    instructions: [
      'Sit or lie comfortably',
      'Place tongue tip behind upper front teeth',
      'Exhale completely through mouth',
      'Close mouth, inhale through nose for 4 counts',
      'Hold breath for 7 counts',
      'Exhale through mouth for 8 counts',
      'Repeat 3-4 times',
    ],
    difficulty: 'beginner',
    duration: {
      min: 60,
      max: 600,
      default: 180,
    },
  },
}

export const TECHNIQUE_IDS = Object.keys(TECHNIQUES)
